initial commit
CQCL/pytket-cirq pull request #1
Opened 2022-10-05 15:51 UTC by cqc-melf

2022-10-05 16:16 UTC, CalMacCQ approved these changes

2022-10-06 10:43 UTC, cqc-melf commented
Will update with PR again after the pytket release is out.

2022-10-06 15:27 UTC, cqc-melf commented
Should include all the changes now including the next release. Github secrets should be updated, too.

2022-10-06 15:40 UTC, cqc-alec requested changes

2022-10-06 15:40 UTC, cqc-alec commented on README.md
> +The [example notebooks](https://github.com/CQCL/pytket-cirq/tree/develop/examples) also demonstrate some of the key features of pytket-cirq.
This folder does not exist.

2022-10-06 15:54 UTC, cqc-melf commented on README.md
> +be executed on Quantinuum's quantum devices.
Thank you, I now made a checklist with all your comments from the PR and the AQT one to check for the other first before I ask for the review, hope I will see more of this error next time myself.

2022-10-06 15:54 UTC, cqc-melf commented on README.md
> +The [example notebooks](https://github.com/CQCL/pytket-cirq/tree/develop/examples) also demonstrate some of the key features of pytket-cirq.
removed, see above

2022-10-06 15:57 UTC, cqc-alec commented on .github/workflows/build-test
> +# - MODULE: single module to test
But GITHUB_WORKSPACE is still used, so that should be left in (just MODULE is no longer used).

2022-10-06 16:06 UTC, cqc-melf commented
Oh, will add that to my checklist, too ... :( tought I had done that...

2022-10-06 16:19 UTC, merged